### ISSUE TITLE
email format validation

### ISSUE THREAD

**Issue by ghost** [gitjs/redux-form-with-ajv#8]
>`{
  "title": "User by user",
  "description": "User created by user",
  "type": "object",
  "additionalProperties": false,
  "required": ["email", "password", "lang", "firstName", "lastName", "phone"],
  "properties": {
    "roleIds": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "objectid": true
      }
    },
    "departmentIds": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "objectid": true
      }
    },
    "functionIds": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "objectid": true
      }
    },
    "email": {
      "type": "string",
      "allOf": [{ "lowercase": true, "trim": true }, { "format": "email" }]
    },
    "password": { "type": "string", "minLength": 6 },
    "lang": {
      "type": "string",
      "allOf": [{ "lowercase": true, "trim": true }, { "enum": ["fr", "en"] }]
    },
    "firstName": {
      "type": "string",
      "allOf": [{ "trim": true }, { "minLength": 1 }]
    },
    "lastName": {
      "type": "string",
      "allOf": [{ "trim": true }, { "minLength": 1 }]
    },
    "phone": {
      "type": "string",
      "allOf": [{ "trim": true }, { "minLength": 1 }]
    }
  }
}
` I

 use redux-form-with-ajv in a redux-form and it seems that there is a problem with the email format validation, when I type something@something there is no error. 

my ajv schema used in the form

where I use the schema

`export default (UserFormRedux = reduxForm({
  form: 'UserFormRedux',
  validate: validate(userAjv, { errorMessage })
})(UserFormRedux));`

**Comment by gitjs** [comment]
You need to pass the option "format: full" to your ajv instance. Its a behavior of ajv itself.

Look at this old issue: https://github.com/epoberezkin/ajv/issues/756
Solved: https://runkit.com/esp/5ad26dff34cee100126093f2

So just do so: 
```
const ajv = new Ajv({
    format: 'full',
    allErrors: true,
    verbose: true
});

export default (UserFormRedux = reduxForm({ form: 'UserFormRedux', validate: validate(userAjv, { ajv, errorMessage }) })(UserFormRedux));
```

**Comment by ghost** [comment]
Thanks for your answer that resolves my problem
